package com.dwarvenpick.app.inspector.providers

import com.dwarvenpick.app.datasource.ConnectionSpec
import com.dwarvenpick.app.datasource.DatasourceEngine
import com.dwarvenpick.app.inspector.InspectedObjectNotFoundException
import com.dwarvenpick.app.inspector.InspectedObjectType
import com.dwarvenpick.app.inspector.ObjectInspectorKeyValue
import com.dwarvenpick.app.inspector.ObjectInspectorObjectRef
import com.dwarvenpick.app.inspector.ObjectInspectorProvider
import com.dwarvenpick.app.inspector.ObjectInspectorSection
import com.dwarvenpick.app.inspector.ObjectInspectorSectionKind
import com.dwarvenpick.app.inspector.ObjectInspectorSectionStatus
import com.dwarvenpick.app.systemhealth.isInsufficientPrivilege
import org.springframework.stereotype.Component
import java.sql.Connection
import java.sql.SQLException

@Component
class VerticaObjectInspectorProvider : ObjectInspectorProvider {
    override val engines: Set<DatasourceEngine> = setOf(DatasourceEngine.VERTICA)

    override fun inspect(
        spec: ConnectionSpec,
        connection: Connection,
        objectRef: ObjectInspectorObjectRef,
    ): List<ObjectInspectorSection> {
        val schema = objectRef.schema.trim()
        val name = objectRef.name.trim()
        if (schema.isBlank() || name.isBlank()) {
            throw IllegalArgumentException("Schema and object name are required.")
        }

        if (!objectExists(connection, schema, name, objectRef.type)) {
            throw InspectedObjectNotFoundException("Object $schema.$name not found.")
        }

        val ddlSection =
            buildSection(
                id = "ddl",
                title = "DDL",
            ) {
                val table =
                    runTableQuery(
                        connection,
                        "SELECT EXPORT_OBJECTS('', ?)",
                        bind = { stmt ->
                            stmt.setString(1, "$schema.$name")
                        },
                        timeoutSeconds = 20,
                    )
                val ddlText =
                    table.rows
                        .firstOrNull()
                        ?.firstOrNull()
                        .orEmpty()
                        .trim()
                if (ddlText.isBlank()) {
                    throw SQLException("EXPORT_OBJECTS did not return DDL.")
                }
                ObjectInspectorSection(
                    id = "ddl",
                    title = "DDL",
                    status = ObjectInspectorSectionStatus.OK,
                    kind = ObjectInspectorSectionKind.TEXT,
                    text =
                        buildString {
                            appendLine("-- Generated by dwarvenpick (best effort)")
                            append("-- Source: EXPORT_OBJECTS")
                            appendLine()
                            appendLine()
                            append(ddlText)
                            if (!ddlText.trimEnd().endsWith(";")) {
                                appendLine()
                                append(";")
                            }
                        },
                )
            }

        val columnsSection =
            buildSection(
                id = "columns",
                title = "Columns",
            ) {
                val table =
                    runTableQuery(
                        connection,
                        """
                        SELECT column_name AS name,
                               data_type AS type,
                               CASE WHEN is_nullable THEN 'YES' ELSE 'NO' END AS nullable,
                               column_default AS default_value,
                               CASE WHEN is_identity THEN 'YES' ELSE 'NO' END AS identity,
                               character_maximum_length AS character_maximum_length,
                               numeric_precision AS numeric_precision,
                               numeric_scale AS numeric_scale
                        FROM v_catalog.columns
                        WHERE table_schema = ? AND table_name = ?
                        ORDER BY ordinal_position
                        """.trimIndent(),
                        bind = { stmt ->
                            stmt.setString(1, schema)
                            stmt.setString(2, name)
                        },
                    )
                ObjectInspectorSection(
                    id = "columns",
                    title = "Columns",
                    status = ObjectInspectorSectionStatus.OK,
                    kind = ObjectInspectorSectionKind.TABLE,
                    table = table,
                )
            }

        val indexesSection =
            buildSection(
                id = "indexes",
                title = "Indexes",
            ) {
                val table =
                    runTableQuery(
                        connection,
                        """
                        SELECT projection_name AS projection,
                               projection_column_name AS column,
                               column_position AS column_position,
                               sort_position AS sort_position,
                               order_by_position AS order_by_position,
                               partition_by_position AS partition_by_position,
                               encoding_type AS encoding_type
                        FROM v_catalog.projection_columns
                        WHERE table_schema = ? AND table_name = ?
                        ORDER BY projection_name, column_position
                        """.trimIndent(),
                        bind = { stmt ->
                            stmt.setString(1, schema)
                            stmt.setString(2, name)
                        },
                    )
                ObjectInspectorSection(
                    id = "indexes",
                    title = "Indexes",
                    status = ObjectInspectorSectionStatus.OK,
                    kind = ObjectInspectorSectionKind.TABLE,
                    table = table,
                )
            }

        val constraintsSection =
            buildSection(
                id = "constraints",
                title = "Constraints",
            ) {
                val table =
                    runTableQuery(
                        connection,
                        """
                        SELECT constraint_name AS name,
                               CASE constraint_type
                                   WHEN 'p' THEN 'PRIMARY KEY'
                                   WHEN 'f' THEN 'FOREIGN KEY'
                                   WHEN 'u' THEN 'UNIQUE'
                                   WHEN 'c' THEN 'CHECK'
                                   ELSE constraint_type
                               END AS type,
                               column_name AS column_name,
                               reference_table_schema AS referenced_schema,
                               reference_table_name AS referenced_table,
                               reference_column_name AS referenced_column,
                               is_enabled AS enabled
                        FROM v_catalog.constraint_columns
                        WHERE table_schema = ? AND table_name = ? AND constraint_type <> 'n'
                        ORDER BY constraint_type, constraint_name, column_name
                        """.trimIndent(),
                        bind = { stmt ->
                            stmt.setString(1, schema)
                            stmt.setString(2, name)
                        },
                    )
                ObjectInspectorSection(
                    id = "constraints",
                    title = "Constraints",
                    status = ObjectInspectorSectionStatus.OK,
                    kind = ObjectInspectorSectionKind.TABLE,
                    table = table,
                )
            }

        val partitionsSection =
            buildSection(
                id = "partitions",
                title = "Partitions",
            ) {
                val partitionColumns =
                    runTableQuery(
                        connection,
                        """
                        SELECT projection_name AS projection,
                               table_column_name AS column_name,
                               partition_by_position AS partition_by_position
                        FROM v_catalog.projection_columns
                        WHERE table_schema = ? AND table_name = ? AND partition_by_position IS NOT NULL
                        ORDER BY projection_name, partition_by_position
                        """.trimIndent(),
                        bind = { stmt ->
                            stmt.setString(1, schema)
                            stmt.setString(2, name)
                        },
                    )

                if (partitionColumns.rows.isEmpty()) {
                    ObjectInspectorSection(
                        id = "partitions",
                        title = "Partitions",
                        status = ObjectInspectorSectionStatus.OK,
                        kind = ObjectInspectorSectionKind.KEY_VALUES,
                        keyValues = listOf(ObjectInspectorKeyValue("partitioned", "false")),
                    )
                } else {
                    ObjectInspectorSection(
                        id = "partitions",
                        title = "Partitions",
                        status = ObjectInspectorSectionStatus.OK,
                        kind = ObjectInspectorSectionKind.TABLE,
                        message = "partitioned=true",
                        table = partitionColumns,
                    )
                }
            }

        val sizeSection =
            buildSection(
                id = "size",
                title = "Size & stats",
            ) {
                val keyValues =
                    runKeyValueQuery(
                        connection,
                        """
                        WITH storage AS (
                            SELECT SUM(row_count) AS row_count,
                                   SUM(used_bytes) AS used_bytes,
                                   SUM(wos_row_count) AS wos_row_count,
                                   SUM(wos_used_bytes) AS wos_used_bytes,
                                   SUM(ros_row_count) AS ros_row_count,
                                   SUM(ros_used_bytes) AS ros_used_bytes
                            FROM v_monitor.projection_storage
                            WHERE anchor_table_schema = ? AND anchor_table_name = ?
                        )
                        SELECT t.create_time AS create_time,
                               t.partition_expression AS partition_expression,
                               s.row_count AS row_count,
                               s.used_bytes AS used_bytes,
                               s.wos_row_count AS wos_row_count,
                               s.wos_used_bytes AS wos_used_bytes,
                               s.ros_row_count AS ros_row_count,
                               s.ros_used_bytes AS ros_used_bytes
                        FROM v_catalog.tables t
                        CROSS JOIN storage s
                        WHERE t.table_schema = ? AND t.table_name = ?
                        """.trimIndent(),
                        bind = { stmt ->
                            stmt.setString(1, schema)
                            stmt.setString(2, name)
                            stmt.setString(3, schema)
                            stmt.setString(4, name)
                        },
                    )
                ObjectInspectorSection(
                    id = "size",
                    title = "Size & stats",
                    status = ObjectInspectorSectionStatus.OK,
                    kind = ObjectInspectorSectionKind.KEY_VALUES,
                    keyValues = keyValues,
                )
            }

        return listOf(
            ddlSection,
            columnsSection,
            indexesSection,
            constraintsSection,
            partitionsSection,
            sizeSection,
        )
    }

    private fun objectExists(
        connection: Connection,
        schema: String,
        name: String,
        type: InspectedObjectType,
    ): Boolean {
        val sql =
            when (type) {
                InspectedObjectType.VIEW ->
                    "SELECT 1 FROM v_catalog.views WHERE table_schema = ? AND table_name = ? LIMIT 1"

                InspectedObjectType.TABLE ->
                    "SELECT 1 FROM v_catalog.tables WHERE table_schema = ? AND table_name = ? LIMIT 1"
            }

        return connection.prepareStatement(sql).use { stmt ->
            stmt.queryTimeout = 10
            stmt.setString(1, schema)
            stmt.setString(2, name)
            stmt.executeQuery().use { rs -> rs.next() }
        }
    }

    private fun buildSection(
        id: String,
        title: String,
        block: () -> ObjectInspectorSection,
    ): ObjectInspectorSection =
        try {
            block()
        } catch (exception: SQLException) {
            if (isInsufficientPrivilege(exception)) {
                ObjectInspectorSection(
                    id = id,
                    title = title,
                    status = ObjectInspectorSectionStatus.INSUFFICIENT_PRIVILEGES,
                    message = "Connection does not have privileges to read ${title.lowercase()}.",
                )
            } else {
                ObjectInspectorSection(
                    id = id,
                    title = title,
                    status = ObjectInspectorSectionStatus.ERROR,
                    message = exception.message ?: "Unable to load ${title.lowercase()}.",
                )
            }
        }
}
